### ISSUE TITLE
Poor design

### ISSUE THREAD

**Issue by Garnek0** [Garnek0/GarnOS#3]
GarnOS has some very big flaws that have been overlooked for quite a long time. I'll list all of the things i've found here, and then i'll start fixing them one by one:
- [ ] The `mlibc` port needs to be rewritten (and PRed, maybe), because currently it is just a botch full of ABI breaks. It also crashes sometimes at random (I may have fixed this, though, i'm not sure).
- [ ] Storing patched `gcc` and `binutils` in repos is not very efficient, so i need to write a fetch-patch-compile script instead.
- [x] Kconfig should be removed. It's just extra clutter.
- [ ] The build system is very messy too, so it needs to be cleaned up.
- [ ] I want GarnOS to be fully portable to other architectures, so i need to make the kernel and modules not revolve around x86_64 (and not make a mess while doing so).
- [ ] There are A LOT of compiler warnings that need fixing.
- [x] `getdents` doesnt work at all.
- [ ] There are a few dragons inside the FAL code, especially the VFS stuff.
- [ ] The DAL is very complicated and unconventional. I'd like to make it more UNIX-like.
- [ ] For whatever reason the OS freaks out and crashes if the boot drive is larger than 300-ish MB.
- [ ] The terminal emulator is incomplete, broken and in need of a redesign.
- [ ] Process blocking is not implemented, so a lot of CPU time is wasted.
- [x] The FAT32 `readdir` routine is unintelligible.
- [ ] Random pagefaults every now and then when loading userspace.

These are all the things i know of. I might stumble upon more in the future and in that case i'll just add them to the bunch.
